instuctorproj/instuctorproj/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('instructapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instuctorproj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name="logout"),
]

instuctorproj/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils import timezone


class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='images/', blank=True, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    password = models.CharField(max_length=128)
    birthday = models.DateField(default=timezone.now)
    email = models.EmailField()
    bio = models.TextField()
    location = models.CharField(max_length=100)
    phone_number = models.CharField(max_length=11)
    # Boolean to decifer between student and teacher
    is_instructor = models.BooleanField(default=False)
    # enrollments to be added once instructapp models are created


    def __str__(self):
        return self.last_name + ', ' + self.first_name

instuctorproj/users/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, reverse
from .models import User
from datetime import datetime
import django.contrib.auth
from django.contrib.auth.decorators import login_required


def register(request):
    if request.method == 'POST':
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        username = request.POST['username']
        password = request.POST['password']
        if 'is_instructor' in request.POST:
            is_instructor = True
        else:
            is_instructor = False
        email = request.POST['email']
        phone_number = request.POST['phone_number']
        location = request.POST['location']
        birthday = request.POST['birthday']
        birthday = datetime.strptime(birthday, '%Y-%m-%d')
        bio = request.POST['bio']
        print(request.POST['bio'])
        # ----------------------------------
        user = User.objects.create_user(username,email,password)
        user.first_name = first_name
        user.last_name = last_name
        user.is_instructor = is_instructor
        user.phone_number = phone_number
        user.birthday = birthday
        user.location = location
        user.bio = bio
        user.save()
    return render(request, ('users/register.html'))

def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = django.contrib.auth.authenticate(request, username=username, password=password)
        if user is not None:
            django.contrib.auth.login(request, user)
            return HttpResponseRedirect(reverse('instructapp:profile_management'))
        else:
            return render(request, 'users/register.html', {'error': 'Incorrect username or password'})
    else:
        return render(request, ('users/register.html'))

@login_required
def logout(request):
    django.contrib.auth.logout(request)
    return HttpResponseRedirect(reverse('users:register'))

instuctorproj/users/templates/users/register.html
{% extends 'instructapp/base.html' %}

{% block content %}

<div id="app" class="container">
    <button @click="regLog">Switch</button>
    <!-- Registration Form -->
    <form v-if="register == true" action="{% url 'users:register' %}" method="POST">
        {%csrf_token%}
        <h1>Registration</h1>
        <div class="row">
            <div class="col">
                <label for="username">Username</label>
                <input id="username" type="text" name="username" class="form-control">
            </div>
            <div class="col">
                <label for="password">Password</label>
                <input id="password" v-model="password" name="password" type="password" class="form-control">
            </div>
            <div class="col">
                <label for="re_password">Re-enter Password</label>
                <input id="re_password" v-model="re_password" name="re_password" type="password" class="form-control">
            </div>
        </div>
        <div class="row d-flex align-items-center">
            <div class="col">
                <label for="first_name">First Name</label>
                <input id="first_name" type="text" name="first_name" class="form-control">
            </div>
            <div class="col">
                <label for="last_name">Last Name</label>
                <input id="last_name" type="text" name="last_name" class="form-control">
            </div>
            <div class="col">
                <label for="instructor">Instructors click here!</label>
                <input id="instructor" name="is_instructor" class="form-check-input" type="checkbox">
            </div>
        </div>
        <div class="row">
            <div class="col">
                <label for="email">E-Mail</label>
                <input name="email" type="email" class="form-control">
            </div>
            <div class="col">
                <label for="phone_number">Phone Number</label>
                <input name="phone_number" type="text" class="form-control">
            </div> 
        </div>

        <div class="row">
            <div class="col">
                <label for="birthday">Birthday</label>
                <input id="birthday" class="form-control" name="birthday" type="date">
            </div>
            <div class="col">
                <label for="location">Location</label>
                <input id="location" class="form-control" type="text" name="location">
            </div>
        </div>
        <div class="row">
            <label for="bio">Biography</label>
            <input type="hidden" name="bio" v-model="editorData"></input>
            <ckeditor v-model="editorData" :config="editorConfig"></ckeditor>
        </div>
        <button type="submit" v-bind:disabled="password != re_password || password === ''" class="btn btn-primary">submit</button>
    </form>
    <!-- Login Form -->
    <form v-if="register == false" action="{% url 'users:login' %}" method="POST">
        {% csrf_token %}
        <h1>Login</h1>
        <div class="bg-danger">{{error}}</div>
        <div class="row">
            <div class="col">
                <label for="user_name">Username:</label>
                <input id="user_name" name="username" type="text" class="form-control">
            </div>
            <div class="col">
                <label for="pass_word">Password:</label>
                <input id="pass_word" type="password" name="password" class="form-control">
            </div>
        </div>
        <button type="submit">Login</button>
    </form>
</div>

<!-- Page JS -->
<script type="text/javascript">
    let app = new Vue({
        el: '#app',
        delimiters: ['[[', ']]'],
        components: {
            // Use the <ckeditor> component in this view.
            ckeditor: CKEditor.component
        },
        data: {
            title: 'Hello World!',
            register: false,
            password: '',
            re_password: '',
            editorData: '<p></p>',
            editorConfig: {},
            l_overview: '<p></p>',

        },
        methods: {
            regLog: function () {
                if (this.register == true) {
                    this.register = false
                } else {
                    this.register = true
                }
                console.log(this.register)
            },
        },
        created: function () {
        }
    })
</script>

{% endblock %}