instuctorproj/instructapp/urls.py
from django.urls import path
from . import views

app_name = 'instructapp'
urlpatterns = [
    path('', views.index, name='index'),
    path('profile_management/', views.profile_management, name='profile_management'),
    path('course_page/<int:course_id>/', views.course_page, name='course_page'),
    path('create_lesson/', views.create_lesson, name="create_lesson"),
    path('get_course/', views.get_course, name="get_course"),
    path('courses_taught/', views.courses_taught, name="courses_taught"),
    path('create_course/', views.create_course, name="create_course"),
    path('profile/<int:user_id>/', views.public_page, name="public_page"),
    path('edit_profile/', views.edit_profile, name="edit_profile"),
    path('picture_upload', views.picture_upload, name="picture_upload"),
    path('course_cataloug', views.course_cataloug, name="course_cataloug"),
    path('enroll/', views.enroll, name="enroll"),
    path('delete_course/', views.delete_course, name="delete_course"),
    path('delete_lesson', views.delete_lesson, name="delete_lesson"),
]

instuctorproj/instuctorproj/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('instructapp.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

instuctorproj/users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name="logout"),
]

instuctorproj/instructapp/models.py
from django.db import models
from users.models import User

# Course Model
class Course(models.Model):
    title = models.CharField(max_length=100)
    overview = models.TextField()
    start_date = models.DateField(null=True)
    instructor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='courses_taught')
    enrolled = models.ManyToManyField(User, related_name='students_enrolled', blank=True)
    price = models.FloatField()

    def __str__(self):
        return self.title

# Lesson Model
class Lesson(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='lessons')
    title = models.CharField(max_length=100)
    overview = models.TextField()
    due_date = models.DateField(null=True)

    def __str__(self):
        return self.title + ' (' + self.course.title + ')'

# Lesson Supporting Media Model
class LessonUploads(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='uploads')
    title = models.CharField(max_length=100)
    media = models.FileField(upload_to='videos/', blank=True, null=True)

    def __str__(self):
        return self.title + ' (' + self.lesson.title + ')'


# Student Submission/Feedback Model
class StudentSubmission(models.Model):
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE, related_name='submissions')
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='submissions')
    submission = models.FileField(upload_to='videos/', blank=True, null=True)
    feedback = models.TextField()

    def __str__(self):
        return self.student + ' (' + self.lesson.title + ')'

instuctorproj/instructapp/views.py
from django.shortcuts import render, reverse
from django.http import HttpResponseRedirect, JsonResponse, HttpResponse
from django.contrib.auth.decorators import login_required
from users.models import User
from .models import Course, Lesson, LessonUploads, StudentSubmission
from datetime import datetime
import json

# Create your views here.
@login_required
def index(request):
    return render(request, 'instructapp/base.html')

def course_cataloug(request):
    course_list = Course.objects.all()
    context = {
        'course_list': course_list
    }
    return render(request, 'instructapp/course_cataloug.html', context)

def course_page(request, course_id):
    context = {
        'course_id':course_id,
    }
    return render(request, 'instructapp/course_page.html', context)

def public_page(request, user_id):
    public_profile = User.objects.get(id=user_id)
    context = {
        'public_profile':public_profile
    }
    return render(request, 'instructapp/public_page.html/', context)

def get_course(request):
    course_id = request.GET['course_id']
    course_info = Course.objects.get(id=course_id)
    enrolled = course_info.enrolled.all()
    enrolled_list =[]
    for student in enrolled:
        enrolled_list.append({
            'student_name':student.last_name+', '+student.first_name,
            'student_id':student.id,
        })
    instructor = course_info.instructor.last_name+', '+course_info.instructor.first_name
    lesson_info = Lesson.objects.filter(course=course_info)
    course_data = {
        'title':course_info.title,
        'overview':course_info.overview,
        'start_date':course_info.start_date,
        'instructor': instructor,
        'instructor_id': course_info.instructor.id,
        'price':course_info.price,
    }
    lessons = []
    for lesson in lesson_info:
        lessons.append({
            'title': lesson.title,
            'overview':lesson.overview,
            'due_date':lesson.due_date,
            'id':lesson.id
        })
    return JsonResponse({'course':course_data, 'lessons':lessons, 'students_enrolled':enrolled_list})

@login_required
def profile_management(request):
    user_profile = request.user
    context = {
        'user_profile':user_profile,
    }
    return render(request, 'instructapp/profile_management.html', context)

@login_required
def picture_upload(request):
    user = request.user
    user.profile_picture = request.FILES['profile_picture']
    user.save()
    return HttpResponseRedirect(reverse('instructapp:profile_management'))

@login_required
def courses_taught(request):
    user = User.objects.get(id=request.GET['user_id'])
    courses_instructing = Course.objects.filter(instructor=user)
    courses_attending = Course.objects.filter(enrolled=user)
    instructing = []
    for course in courses_instructing:
        instructing.append({
            'title':course.title,
            'id': course.id,
            'start_date': course.start_date,
        })
    attending = []
    for course in courses_attending:
        attending.append({
            'title': course.title,
            'id': course.id,
            'start_date': course.start_date,
        })
    return JsonResponse({'instructing':instructing, 'attending':attending})

@login_required
def create_lesson(request):
    data = json.loads(request.body)
    course = Course.objects.get(id=data['course_id'])
    title = data['title']
    overview = data['overview']
    due_date = data['due_date']
    due_date = datetime.strptime(due_date, '%Y-%m-%d')
    lesson_set = Lesson(course=course, title=title, overview=overview, due_date=due_date)
    lesson_set.save()
    return HttpResponse('ok')

@login_required
def create_course(request):
    data = json.loads(request.body)
    title = data['title']
    overview = data['overview']
    start_date  = data['start_date']
    start_date = datetime.strptime(start_date, '%Y-%m-%d')
    instructor = request.user
    price = data['price']
    course_set = Course(title=title,overview=overview,start_date=start_date,instructor=instructor,price=price)
    course_set.save()
    return HttpResponse('ok')

@login_required
def edit_profile(request):
    data = json.loads(request.body)
    user_set = request.user
    user_set.bio = data['bio']
    user_set.first_name = data['first_name']
    user_set.last_name = data['last_name']
    user_set.email = data['email']
    user_set.phone_number = data['phone_number']
    user_set.location = data['location']
    user_set.save()
    return HttpResponse('ok')

@login_required
def enroll(request):
    data = json.loads(request.body)
    course = Course.objects.get(id=data['course_id'])
    course.enrolled.add(request.user)
    course.save()
    return HttpResponse('ok')

@login_required
def delete_course(request):
    data = json.loads(request.body)
    course = Course.objects.get(id=data['course'])
    course.delete()
    return HttpResponse('ok')

@login_required
def delete_lesson(request):
    data = json.loads(request.body)
    print(data)
    lesson = Lesson.objects.get(id=data["lesson"])
    lesson.delete()
    return HttpResponse('ok')

instuctorproj/instructapp/templates/instructapp/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello World!</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- CKeditor Script -->
    <script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/ckeditor4-vue@1.3.1/dist/ckeditor.min.js"></script>
    <!-- Google Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Dancing+Script">
    <!-- Vue JS -->
    <script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
    <!-- Axios JS -->
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <!-- Additional Styling -->
    <style>
        html,
        body {
            background-color: #DCE2C8;
            padding-bottom: 30px;
        }

        nav {
            background-color: #A8DCD1;
        }

        #title_bar {
            font-family: Dancing Script;
            color: rgb(212, 185, 94) !important;
        }

        .footer {
            display: flex;
            align-items: center;
            left: 0;
            bottom: 0;
            width: 100%;
            height: 5%;
            background-color: #A8DCD1;
            color: #F96900;
            text-align: start;
            position: fixed;
        }
    </style>
</head>

<body>
    <!-- Page Content -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid d-flex justify-content-between">
            <a id="title_bar" class="navbar-brand" href="#">Instructor's Assisstant</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item d-flex align-items-center">
                        <div class="nav-link">Welcome, {{user.first_name}}</div>
                    </li>
                    {%endif%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructapp:profile_management' %}">Home</a>
                    </li>
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructapp:public_page' user.id %}">Public Page</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'instructapp:course_cataloug' %}">Course Cataloug</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Login</a>
                    </li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}
    <div class="footer">
        <span class="ms-4">(C) Class Eagle 2021</span>
    </div>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

</body>

</html>

instuctorproj/instructapp/templates/instructapp/course_cataloug.html
{% extends 'instructapp/base.html' %}

{% block content %}
<style>
    #cataloug_title {
        font-family: Dancing Script;
        font-size: 50px;
    }
    #cataloug_table {
        border:double;
        border-color:#F17F29;
        background-color: #A8DCD1;
        border-width: 10px;
        border-radius: 20px;
    }
    #course_button {
        background-color: #65DEF1;
    }
</style>

<div class="container">
    <div class="row">
        <div id="cataloug_title" class="text-center">Course Cataloug</div>
    </div>
    <hr>
    <div class="row">
        <table id="cataloug_table" class="table">
            <thead>
                <tr class="text-center">
                    <th scope="col">Course</th>
                    <th scope="col">Instructor</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for course in course_list%}
                <tr>
                    <td>{{course.title}}</td>
                    <td>{{course.instructor}}</td>
                    <td><a id="course_button" class="btn" href="{% url 'instructapp:course_page' course.id %}">Course Page</a></td>
                </tr>
                {%endfor%}
            </tbody>
        </table>
    </div>

</div>

{%endblock%}

instuctorproj/instructapp/templates/instructapp/profile_management.html
{% extends 'instructapp/base.html' %}

{% block title %}Hello!{% endblock %}

{% block content %}
<style>
    #welcome {
        font-family: Dancing Script;
        color: #F17F29;
    }

    #courses_list {
        color: #F17F29;
        font-family: Dancing Script;
        text-align: center;
    }

    #profile_card {
        width: 100%;
        background-color: #A8DCD1;
    }

    #teaching_list {
        background-color: #dce2c8;
    }

    #courses {
        background-color: #A8DCD1;
        border: double;
        border-width: 5px;
        border-radius: 20px;
        border-color: #F17F29;
    }
</style>
<div id="profile_app" class="container">
    <div class="row d-flex align-items-center">
        <div class="col">
            <div id="profile_card" class="card mt-3 rounded-2">
                <div class="col pt-2 d-flex justify-content-center">
                    {% if user.profile_picture %}
                    <img class="img-fluid border border-5 rounded-circle" src="{{user.profile_picture.url}}"
                        width="350">
                    {%else%}
                    <form action="{% url 'instructapp:picture_upload' %}" method="POST" enctype="multipart/form-data">
                        {%csrf_token%}
                        <div class="mb-3">
                            <label for="formFile" class="form-label">Add a Profile Picture:</label>
                            <input class="form-control" name="profile_picture" type="file">
                            <button type="submit" class="btn-primary form-control">Submit</button>
                        </div>
                    </form>
                    {%endif%}
                </div>
                <div class="card-body d-flex justify-content-center">
                    <h1 id="welcome">Welcome, {{user.first_name}}</h1>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="row">
                <!-- Modal Launch button for Course Creation -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#CourseCreation">Create Course</button>
            </div>
            <div class="row mt-2">
                <!-- Modal Launch button for Edit Profile -->
                <button type="button" class="btn btn-primary" data-bs-toggle="modal"
                    data-bs-target="#EditProfileModal">Edit Profile</button>
            </div>

        </div>
    </div>



    <div class="row">
        <!-- list for courses instructing -->
        <div id="courses" class="col mt-2 mx-1 mb-1">
            <h3 id="courses_list"><u>Courses Instructing:</u></h3>
            <div v-if="instructing.length > 0">
                <ul v-for="(course, index) in instructing" class="list-group list-group-flush">
                    <li id="teaching_list"
                        class="list-group-item d-flex justify-content-between align-items-center my-1 rounded-3">
                        <span>[[course.title]]</span>
                        <div>
                            <a class="btn btn-success" :href="'/course_page/'+course.id+'/'">Course Page</a>
                            <button class="btn btn-warning" v-on:click="deleteCourse(course.id)">Delete Course</button>
                        </div>
                    </li>
                </ul>
            </div>
            <div v-else>
                <ul class="list-group list-group-flush">
                    <li id="teaching_list"
                        class="list-group-item d-flex justify-content-between align-items-center my-1 rounded-3">
                        You are currently not instructing any courses.
                    </li>
                </ul>
            </div>
        </div>
        <!-- list for courses attending -->
        <div id="courses" class="col mt-2 mx-1 mb-1">
            <h3 id="courses_list"><u>Courses Attending:</u></h3>
            <div v-if="attending.length > 0">
                <ul v-for="(course, index) in attending" class="list-group list-group-flush">
                    <li id="teaching_list"
                        class="list-group-item d-flex justify-content-between align-items-center my-1 rounded-3">
                        <span>[[course.title]]</span><a class="btn btn-warning"
                            :href="'/course_page/'+course.id+'/'">Course Page</a>
                    </li>
                </ul>
            </div>
            <div v-else>
                <ul class="list-group list-group-flush">
                    <li id="teaching_list"
                        class="list-group-item d-flex justify-content-between align-items-center my-1 rounded-3">
                        You are currently not attending any courses.
                    </li>
                </ul>
            </div>

        </div>
    </div>

    <!-- Modal for Course Creation -->
    <div class="modal fade" id="CourseCreation" tabindex="-1" aria-labelledby="CourseCreationLabel" aria-hidden="true">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="CourseCreationLabel">Course Creation</h5>
                </div>
                <div class="modal-body">
                    <div>
                        <label for="title">Title:</label>
                        <input v-model="title" class="form-control" id="title" type="text">
                    </div>
                    <div>
                        <label for="overview">Overview:</label>
                        <ckeditor v-model="overview" :config="editorConfig"></ckeditor>
                    </div>
                    <div>
                        <label for="start_date">Start Date:</label>
                        <input v-model="start_date" class="form-control" type="date">
                    </div>
                    <div class="input-group mb-3">
                        <span class="input-group-text">$</span>
                        <input type="number" class="form-control" v-model="price"
                            aria-label="Amount (to the nearest dollar)">
                        <span class="input-group-text">.00</span>
                    </div>
                    <button type="submit" data-bs-dismiss="modal" @click="createCourse" class="btn btn-primary">Create
                        Course</button>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal for Editing Profile Information -->
    <div class="modal fade" id="EditProfileModal" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="EditProfileModalLabel">Edit Profile</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <label for="edit_first">First Name</label>
                            <input class="form-control" id="edit_first" type="text" v-model="editFirstname">
                        </div>
                        <div class="col">
                            <label for="edit_last">Last Name</label>
                            <input class="form-control" id="edit_last" type="text" v-model="editLastname">
                        </div>
                        <div class="col">
                            <label for="edit_location">Location</label>\
                            <input id="edit_location" v-model="editLocation" class="form-control" type="text">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col">
                            <label for="edit_email">E-Mail</label>
                            <input class="form-control" id="edit_email" type="email" v-model="editEmail">
                        </div>
                        <div class="col">
                            <label for="edit_phone">Phone Number</label>
                            <input class="form-control" type="number" v-model="editPhone" id="edit_phone">
                        </div>
                    </div>
                    <div class="row">
                        <label for="edit_bio">Bio</label>
                        <ckeditor id="edit_bio" v-model="editBio" :config="editorConfig"></ckeditor>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" v-on:click="editProfile" data-bs-dismiss="modal" class="btn btn-primary">Save
                        changes</button>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let app = new Vue({
        el: '#profile_app',
        delimiters: ['[[', ']]'],
        components: {
            // Use the <ckeditor> component in this view.
            ckeditor: CKEditor.component
        },
        data: {
            editorConfig: {},
            instructing: [],
            attending: [],
            title: '',
            overview: '<p></p>',
            start_date: '',
            price: '',
            editFirstname: '{{user.first_name}}',
            editLastname: '{{user.last_name}}',
            editEmail: '{{user.email}}',
            editPhone: '{{user.phone_number}}',
            editLocation: '{{user.location}}',
            editBio: `{{user.bio|safe}}`,
        },
        methods: {
            getInstructed: function () {
                axios({
                    method: "get",
                    url: "{% url 'instructapp:courses_taught' %}",
                    params: {
                        user_id: "{{user.id}}"
                    },
                }).then((response) => {
                    console.log(response.data)
                    this.instructing = response.data['instructing']
                    this.attending = response.data['attending']
                })
            },
            clearFields: function () {
                this.title = ''
                this.overview = '<p></p>'
                this.start_date = ''
                this.price = ''
            },
            createCourse: function () {
                axios({
                    method: "post",
                    url: "{% url 'instructapp:create_course' %}",
                    headers: { 'X-CSRFToken': '{{ csrf_token}}' },
                    data: {
                        title: this.title,
                        overview: this.overview,
                        start_date: this.start_date,
                        price: this.price,
                    }
                }).then((response) => {
                    this.getInstructed()
                    this.clearFields()
                })
            },
            editProfile: function () {
                axios({
                    method: "post",
                    url: "{% url 'instructapp:edit_profile' %}",
                    headers: { 'X-CSRFToken': '{{ csrf_token }}' },
                    data: {
                        username: this.editUsername,
                        first_name: this.editFirstname,
                        last_name: this.editLastname,
                        email: this.editEmail,
                        phone_number: this.editPhone,
                        location: this.editLocation,
                        bio: this.editBio,
                        password: this.password,
                    }
                }).then((response) => {
                    console.log(response.data)
                })
            },
            deleteCourse: function(course_id){
                axios({
                    method: "post",
                    url: "{% url 'instructapp:delete_course' %}",
                    headers: {'X-CSRFToken': '{{ csrf_token }}'},
                    data: {
                        course: course_id
                    }
                }).then((response) =>{
                    this.getInstructed()
                })
            }

        },
        created: function () {
            this.getInstructed()
        }
    })
</script>
{% endblock %}

instuctorproj/instructapp/templates/instructapp/public_page.html
{% extends 'instructapp/base.html' %}

{% block content %}
<style>
    #profile_card {
        width: 100%;
        background-color: #A8DCD1;
        order: double;
        border-width: 5px;
        border-color: #F17F29;
        border-radius: 20px;
        padding: 15px;
    }

    #info_card_items {
        background-color: #F17F29;
        width: 100%;
    }

    #about_me {
        background-color: #A8DCD1;
        border: double;
        border-width: 5px;
        border-color: #F17F29;
        border-radius: 20px;
        padding: 15px;
    }
    #info card {
        width:100%
    }
</style>

<div class="container">
    <div class="row row d-flex align-items-center">
        <div class="col">
            <div id="profile_card" class="card mt-3 rounded-2">
                <div class="col pt-2 d-flex justify-content-center">
                    {% if public_profile.profile_picture%}
                    <img class="img-fluid border border-5 rounded-circle" src="{{public_profile.profile_picture.url}}"
                        width="350">
                    {% else %}
                    <h3>This user has not uploaded an image</h3>
                    {%endif%}
                </div>
                <div class="card-body d-flex justify-content-center">
                    <h2>{{public_profile.first_name}} {{public_profile.last_name}}</h2>
                </div>
            </div>
            <!-- basic information -->
        </div>
        <div class="col">
            <div id="info_card" class="card">
                <div class="card-header">
                    General Information
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{public_profile.username}}</li>
                    <li class="list-group-item">{{public_profile.birthday}}</li>
                    <li class="list-group-item">{{public_profile.email}}</li>
                    <li class="list-group-item">{{public_profile.phone_number}}</li>
                </ul>
            </div>
        </div>
        <hr class="mt-3">
        <div id="about_me" class="row mt-3">
            <!-- Bio section -->
            {{public_profile.bio|safe}}
        </div>
    </div>


    {%endblock%}